<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" PrivateAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" PrivateAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common"  PrivateAssets="runtime" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" PrivateAssets="runtime" />
  </ItemGroup>

</Project>
